import path from "path";
import prettier from "prettier";
import { swaggerVersion } from "./utils";
import { transformAll } from "./transform/index";
export * from "./types/index";
export const WARNING_MESSAGE = `/**
* This file was auto-generated by openapi-typescript.
* Do not make direct changes to the file.
*/


`;
export default function swaggerToTS(schema, options) {
    const version = (options && options.version) || swaggerVersion(schema);
    let output = `${WARNING_MESSAGE}
  ${transformAll(schema, { version, rawSchema: options && options.rawSchema })}
`;
    let prettierOptions = { parser: "typescript" };
    if (options && options.prettierConfig) {
        try {
            const userOptions = prettier.resolveConfig.sync(path.resolve(process.cwd(), options.prettierConfig));
            prettierOptions = {
                ...prettierOptions,
                ...userOptions,
            };
        }
        catch (err) {
            console.error(`❌ ${err}`);
        }
    }
    return prettier.format(output, prettierOptions);
}
